version: '3.8'
services:
  database:
    container_name: horseDB
    image: mongo:latest
    networks:
      - backend
    ports:
      - 27018:27017
    volumes:
      - dataDB:/data/db
  server:
    build: ./
    networks:
      - backend
    container_name: horseServer
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    depends_on:
      - database
networks:
  backend:
volumes:
  dataDB:
